#server.port=8888
#spring.application.name=CONFIG-SERVICE
#spring.cloud.config.server.git.uri=https://github.com/harshilahir1010/config-microservice
#spring.cloud.config.server.git.clone-on-start=true 

server:
  port: 8888
  
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/harshilahir1010/config-microservice
          clone-on-start: true